const tableData = [
    {
      date: '2023-10-01',
      divisionNumber: 1,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-02',
      divisionNumber: 2,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-10-03',
      divisionNumber: 3,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-04',
      divisionNumber: 4,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-05',
      divisionNumber: 5,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-06',
      divisionNumber: 6,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-07',
      divisionNumber: 7,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-08',
      divisionNumber: 8,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-09',
      divisionNumber: 9,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-10',
      divisionNumber: 10,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-11',
      divisionNumber: 11,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-12',
      divisionNumber: 12,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-13',
      divisionNumber: 13,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-14',
      divisionNumber: 14,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-15',
      divisionNumber: 15,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-16',
      divisionNumber: 16,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-17',
      divisionNumber: 17,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-18',
      divisionNumber: 18,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-19',
      divisionNumber: 19,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-20',
      divisionNumber: 20,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-21',
      divisionNumber: 21,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-22',
      divisionNumber: 22,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-23',
      divisionNumber: 23,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-24',
      divisionNumber: 24,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-25',
      divisionNumber: 25,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-26',
      divisionNumber: 26,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },{
      date: '2023-10-27',
      divisionNumber: 27,
      divisionName: 'Division A',
      subdivision: 'Subdivision 1',
      subtractionCount: 10,
      damageCount: 5,
      damagePercentage: '50%',
    },
    {
      date: '2023-10-28',
      divisionNumber: 28,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-10-29',
      divisionNumber: 29,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-10-30',
      divisionNumber: 30,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-10-31',
      divisionNumber: 31,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-01',
      divisionNumber: 32,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-02',
      divisionNumber: 33,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-03',
      divisionNumber: 34,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-04',
      divisionNumber: 35,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-05',
      divisionNumber: 36,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-06',
      divisionNumber: 37,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-07',
      divisionNumber: 38,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-08',
      divisionNumber: 39,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-09',
      divisionNumber: 40,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-10',
      divisionNumber: 41,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-11',
      divisionNumber: 42,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-12',
      divisionNumber: 43,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-13',
      divisionNumber: 44,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-14',
      divisionNumber: 45,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-15',
      divisionNumber: 46,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-16',
      divisionNumber: 47,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-17',
      divisionNumber: 48,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-18',
      divisionNumber: 49,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-19',
      divisionNumber: 50,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-20',
      divisionNumber: 51,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-21',
      divisionNumber: 52,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-22',
      divisionNumber: 53,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-23',
      divisionNumber: 54,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-24',
      divisionNumber: 55,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-25',
      divisionNumber: 56,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-26',
      divisionNumber: 57,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-27',
      divisionNumber: 58,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-28',
      divisionNumber: 59,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-29',
      divisionNumber: 60,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    },
    {
      date: '2023-11-30',
      divisionNumber: 61,
      divisionName: 'Division B',
      subdivision: 'Subdivision 2',
      subtractionCount: 15,
      damageCount: 3,
      damagePercentage: '20%',
    }

  ]; 
  export default tableData;